let C=[]; let currentCourse=1; let currentModule=0; let exam=null;
const pages=[...document.querySelectorAll('.page')], $=id=>document.getElementById(id);
const storeKey='ssTrainingV3';
const state=JSON.parse(localStorage.getItem(storeKey)||'{"courses":{},"profile":{"name":"SS Learner"},"entitlements":{},"integrity":[]}');
let PREVIEW=new URLSearchParams(location.search).get('preview')==='1'||sessionStorage.getItem('ssPreview')==='1';
function save(){localStorage.setItem(storeKey,JSON.stringify(state))}
function go(id){pages.forEach(p=>p.classList.remove('active'));$(id)?.classList.add('active');scrollTo(0,0)}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
function cs(id){return state.courses[id]||(state.courses[id]={completed:[],answers:{},reflections:{},started:Date.now(),finalScore:null,feedback:null,attempts:[]})}
function owned(id){return PREVIEW||state.entitlements[id]?.status==='paid'}
function logIntegrity(type,extra={}){state.integrity.push({type,course:currentCourse,at:new Date().toISOString(),...extra});save()}
fetch('courses.json').then(r=>r.json()).then(d=>{C=d;draw();renderPortal()});

function card(c){let s=cs(c.id),d=SS_CONTENT[c.id],pct=Math.round((s.completed.length/d.modules.length)*100);return `<article class="card" data-id="${c.id}"><small>${c.tag.toUpperCase()} • ${c.hours} CPD HOURS</small><h3>${c.title}</h3><p>${c.desc}</p>${owned(c.id)?`<div class="mini-progress"><b style="width:${pct}%"></b></div>`:''}<footer><b>£${c.price}</b><button aria-label="View course">→</button></footer></article>`}
function draw(){featured.innerHTML=C.slice(0,3).map(card).join('');grid.innerHTML=C.map(card).join('');document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>detail(+x.dataset.id))}
function detail(id){let c=C.find(x=>x.id===id),d=SS_CONTENT[id],isOwned=owned(id);detailbox.innerHTML=`<div class="detail"><div class="detailtop"><div><i>${c.tag.toUpperCase()} • ${c.hours} CPD HOURS</i><h1>${c.title}</h1><p>${c.desc}</p><p>This course uses advanced teaching, applied professional judgement, written evidence and a controlled final assessment.</p></div><aside class="buy"><b>£${c.price}</b><span>${c.hours} CPD hours</span><span>${d.modules.length} in-depth learning stages</span><span>4-option applied knowledge checks</span><span>Written professional reflection</span><span>Closed-learning final assessment</span><span>80% pass requirement</span><button class="cta" id="courseAction">${isOwned?'Start / continue course →':`Enrol now — £${c.price}`}</button>${PREVIEW?'<small>Admin preview mode is ON.</small>':''}</aside></div><div class="twocol"><section><h2>What you'll develop</h2><ul>${d.outcomes.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><h2>Course pathway</h2><ol>${d.modules.map((x,i)=>`<li>${String(i+1).padStart(2,'0')} ${x.title}</li>`).join('')}</ol></section></div></div>`;go('detail');$('courseAction').onclick=()=>isOwned?openCourse(id):beginCheckout(id)}
function beginCheckout(id){let c=C.find(x=>x.id===id);detailbox.innerHTML+=`<div class="payment-note"><h2>Secure enrolment</h2><p><b>${c.title}</b> will be unlocked only after the payment provider confirms payment against the signed-in learner account.</p><p>This build deliberately does not fake a live payment. Connect the server-side Stripe Checkout session + webhook/Appwrite Function before launch; no secret key belongs in GitHub.</p>${PREVIEW?`<button class="soft" id="testUnlock">Preview unlock this course</button>`:''}</div>`;if(PREVIEW&&$('testUnlock'))$('testUnlock').onclick=()=>{state.entitlements[id]={status:'paid',source:'admin-preview',at:new Date().toISOString()};save();draw();detail(id)}}
function openCourse(id,idx){if(!owned(id))return detail(id);currentCourse=id;let s=cs(id),d=SS_CONTENT[id],max=Math.min(s.completed.length,d.modules.length-1);let requested=idx??max;if(requested>max){alert('Complete the current stage before moving forward. You can revisit any completed stage at any time.');requested=max}currentModule=Math.max(0,requested);renderLesson();go('lesson')}
function renderLesson(){let d=SS_CONTENT[currentCourse],m=d.modules[currentModule],s=cs(currentCourse);lesson.innerHTML=`<button class="back" id="dashBack">← Dashboard</button><div class="pagehero"><i>${d.short.toUpperCase()} • STAGE ${String(currentModule+1).padStart(2,'0')}</i><h1>${m.title}<br><em>${m.subtitle}</em></h1><p>${m.intro}</p></div><div class="learning"><div>${videoBlock(m)}<article><i>ADVANCED LEARNING</i><h2>${m.heading}</h2>${m.body.map(p=>`<p>${p}</p>`).join('')}${m.points?`<ul class="learn-list">${m.points.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}<blockquote>${m.takeaway}</blockquote></article>${quizBlock(m)}${taskBlock(m,s)}<div class="lesson-actions"><button class="soft" id="prevMod" ${currentModule===0?'disabled':''}>← Previous</button><button class="cta" id="completeMod">${s.completed.includes(currentModule)?'Completed ✓':'Complete stage'}</button><button class="soft" id="nextMod" ${(currentModule===d.modules.length-1||!s.completed.includes(currentModule))?'disabled':''}>Next →</button></div>${currentModule===d.modules.length-1?`<article class="finalbox"><i>FINAL ASSESSMENT</i><h2>Ready for the controlled assessment?</h2><p>Once started, learning navigation is removed. The assessment draws 15 questions from a larger bank, randomises question and answer order, requires 80%, and records focus-loss/paste attempts for integrity review.</p><button class="cta" id="startExam">Start final assessment →</button></article>`:''}</div><aside><i>COURSE PATHWAY</i>${d.modules.map((x,i)=>`<button class="path ${i===currentModule?'current':''} ${s.completed.includes(i)?'done':''} ${i>s.completed.length?'locked':''}" data-mod="${i}">${s.completed.includes(i)?'✓':'○'} ${String(i+1).padStart(2,'0')} ${x.title}</button>`).join('')}<div class="help"><b>Need support?</b><small>Your tutor is for support and escalation. The learning remains available for recap before the final assessment.</small><button id="askTutor">Ask tutor →</button></div></aside></div>`;
$('dashBack').onclick=()=>{renderPortal();go('portal')};document.querySelectorAll('[data-mod]').forEach(b=>b.onclick=()=>openCourse(currentCourse,+b.dataset.mod));$('prevMod').onclick=()=>openCourse(currentCourse,currentModule-1);$('nextMod').onclick=()=>openCourse(currentCourse,currentModule+1);$('completeMod').onclick=()=>completeStage(m);$('askTutor').onclick=()=>openTutor(currentCourse);wireQuiz(m);wireTask(m,s);if($('startExam'))$('startExam').onclick=startExam}
function videoBlock(m){return `<div class="video">${m.video?`<iframe src="${m.video}" title="SS Training course video" allowfullscreen></iframe>`:`<b>▶</b><span>SS TRAINING VIDEO</span><small>High-end demonstration / information video slot ready. Add the approved video URL to learning-data.js.</small>`}</div>`}
function quizBlock(m){return `<article><i>APPLIED KNOWLEDGE CHECK</i><h2>${m.quiz.q}</h2>${m.quiz.a.map((a,i)=>`<label><input type="radio" name="stageq" value="${i}"> ${a}</label>`).join('')}<button class="cta" id="checkStage">Check answer</button><p id="stageResult"></p></article>`}
function wireQuiz(m){$('checkStage').onclick=()=>{let q=document.querySelector('input[name=stageq]:checked');if(!q)return $('stageResult').textContent='Choose the best answer first.';let ok=+q.value===m.quiz.correct;$('stageResult').textContent=ok?'Correct — '+m.quiz.explain:'Not yet. Review the reasoning in this stage before trying again.';if(ok){cs(currentCourse).answers[currentModule]=true;save()}}}
function taskBlock(m,s){return `<article><i>PROFESSIONAL EVIDENCE</i><h2>${m.task}</h2><textarea id="reflection" class="no-paste" placeholder="Write your own answer here. Paste is disabled for assessed reflection.">${s.reflections[currentModule]||''}</textarea><button class="soft" id="saveReflection">Save progress</button><small id="saveNote"></small></article>`}
function wireTask(m,s){let r=$('reflection');r.addEventListener('paste',e=>{e.preventDefault();logIntegrity('reflection-paste-blocked',{module:currentModule});alert('Paste is disabled for this reflection. Please write the answer in your own words.')});$('saveReflection').onclick=()=>{s.reflections[currentModule]=r.value.trim();save();$('saveNote').textContent='Saved on this device ✓'}}
function completeStage(m){let s=cs(currentCourse);if(!s.answers[currentModule])return alert('Please pass the applied knowledge check first.');let v=$('reflection').value.trim();if(v.length<120)return alert('Please provide at least 120 words of professional reasoning for this activity.');s.reflections[currentModule]=v;if(!s.completed.includes(currentModule))s.completed.push(currentModule);s.completed.sort((a,b)=>a-b);save();draw();renderLesson();alert('Stage completed and saved ✓ You can now continue to the next stage.')}
function shuffled(a){return a.map(v=>({v,r:Math.random()})).sort((a,b)=>a.r-b.r).map(x=>x.v)}
function startExam(){let d=SS_CONTENT[currentCourse],s=cs(currentCourse);if(s.completed.length<d.modules.length)return alert('Complete every learning stage before starting the final assessment.');let picked=shuffled(d.final.map((q,i)=>({...q,_id:i}))).slice(0,d.assessmentSettings?.questionsPerAttempt||15).map(q=>{let pairs=q.a.map((a,i)=>({a,ok:i===q.correct}));pairs=shuffled(pairs);return {...q,choices:pairs}});exam={course:currentCourse,questions:picked,started:Date.now(),focusLoss:0,pasteAttempts:0};renderExam();go('lesson')}
function renderExam(){let c=C.find(x=>x.id===currentCourse);lesson.innerHTML=`<div class="exam-shell"><div class="exam-head"><i>SS TRAINING • CONTROLLED FINAL ASSESSMENT</i><h1>${c.title}</h1><p>Closed-learning mode. Choose the BEST professional response. Learning pages are unavailable until you submit or leave the assessment.</p></div><div class="exam-warning">Copy, cut, paste and right-click are disabled inside this assessment. Leaving the tab/window is logged for integrity review.</div>${exam.questions.map((q,n)=>`<article class="finalq"><b>${n+1}. ${q.q}</b>${q.choices.map((x,i)=>`<label><input type="radio" name="eq${n}" value="${i}"> ${x.a}</label>`).join('')}</article>`).join('')}<button class="cta" id="submitExam">Submit final assessment</button><button class="soft" id="leaveExam">Leave without submitting</button></div>`;wireExamSecurity();$('submitExam').onclick=submitExam;$('leaveExam').onclick=()=>{if(confirm('Leave the assessment? This attempt will not be marked.')){logIntegrity('exam-abandoned');exam=null;openCourse(currentCourse,SS_CONTENT[currentCourse].modules.length-1)}}}
function wireExamSecurity(){let shell=document.querySelector('.exam-shell');['copy','cut','paste','contextmenu'].forEach(type=>shell.addEventListener(type,e=>{e.preventDefault();if(type==='paste')exam.pasteAttempts++;logIntegrity('exam-'+type+'-blocked')}));document.addEventListener('visibilitychange',examVisibility,{once:true});window.addEventListener('blur',examBlur,{once:true})}
function examVisibility(){if(exam&&document.hidden){exam.focusLoss++;logIntegrity('exam-tab-hidden')}}
function examBlur(){if(exam){exam.focusLoss++;logIntegrity('exam-window-blur')}}
function submitExam(){let score=0,answered=0;exam.questions.forEach((q,n)=>{let x=document.querySelector(`input[name=eq${n}]:checked`);if(x){answered++;if(q.choices[+x.value].ok)score++}});if(answered<exam.questions.length)return alert('Please answer every question before submitting.');let pct=Math.round(score/exam.questions.length*100),s=cs(currentCourse);s.finalScore=pct;s.attempts.push({date:new Date().toISOString(),score:pct,questions:exam.questions.map(q=>q._id),focusLoss:exam.focusLoss,pasteAttempts:exam.pasteAttempts});save();let passed=pct>=80;lesson.innerHTML=`<div class="exam-result"><i>ASSESSMENT RESULT</i><h1>${pct}%</h1><h2>${passed?'Pass ✓':'Further study required'}</h2><p>${passed?'You have met the knowledge-assessment threshold. Complete course feedback to unlock the certificate.':'Review the learning before making another attempt. A new selection/order of questions will be used.'}</p><p>Integrity record: ${exam.focusLoss} focus event(s), ${exam.pasteAttempts} paste attempt(s).</p><button class="cta" id="returnCourse">Return to course →</button></div>`;exam=null;$('returnCourse').onclick=()=>openCourse(currentCourse,SS_CONTENT[currentCourse].modules.length-1)}
function renderPortal(){if(!C.length)return;let ownedCourses=C.filter(c=>owned(c.id)),active=ownedCourses.find(c=>cs(c.id).completed.length)||ownedCourses[0];$('portal').innerHTML=`<div class="top"><div><i>LEARNER PORTAL</i><h1>Welcome back.</h1></div><button class="soft" id="signout">Sign out</button></div><div class="portal"><aside><button class="side active">◉ My Learning</button><button class="side" id="assessmentsBtn">○ Assessments</button><button class="side" id="tutorBtn">○ Tutor Support</button><button class="side" id="certBtn">○ Certificates</button><button class="side" id="portfolioBtn">○ Portfolio</button></aside><div>${active?portalCourse(active):'<div class="continue empty-learning"><h2>No courses enrolled yet</h2><p>Choose a course and complete secure enrolment to unlock learning.</p><button class="cta" id="browseCourses">Browse courses →</button></div>'}<div id="portalPanel" class="portal-panel"></div></div></div>`;$('signout').onclick=()=>go('home');if($('browseCourses'))$('browseCourses').onclick=()=>go('courses');$('assessmentsBtn').onclick=()=>portalPanel('assess');$('tutorBtn').onclick=()=>active?openTutor(active.id):null;$('certBtn').onclick=()=>portalPanel('cert');$('portfolioBtn').onclick=()=>portalPanel('portfolio')}
function portalCourse(active){let s=cs(active.id),d=SS_CONTENT[active.id],pct=Math.round(s.completed.length/d.modules.length*100);return `<div class="continue"><i>CONTINUE LEARNING</i><h2>${active.title}</h2><p>Stage ${Math.min(s.completed.length+1,d.modules.length)} — ${d.modules[Math.min(s.completed.length,d.modules.length-1)].title}</p><div class="progress"><b style="width:${pct}%"></b></div><small>${pct}% complete • ${s.completed.length}/${d.modules.length} stages complete</small><button class="cta" id="continueCourse">Continue →</button></div><div class="stats"><span><b>${s.completed.length}</b>Stages</span><span><b>${s.finalScore??'—'}${s.finalScore!==null?'%':''}</b>Final score</span><span><b>${s.attempts.length}</b>Assessment attempts</span><span><b>Available</b>Tutor support</span></div>`}
function portalPanel(type){let ownedC=C.filter(c=>owned(c.id)),out='';if(type==='assess')out='<h2>Assessments</h2>'+ownedC.map(c=>`<p><b>${c.title}</b> — ${cs(c.id).finalScore===null?'Not attempted':cs(c.id).finalScore+'%'}</p>`).join('');if(type==='cert')out='<h2>Certificates</h2>'+ownedC.map(c=>`<p><b>${c.title}</b> — ${cs(c.id).finalScore>=80?'Pass recorded — certificate activates after feedback':'Not yet unlocked'}</p>`).join('');if(type==='portfolio')out='<h2>Learning portfolio</h2>'+ownedC.map(c=>`<p><b>${c.title}</b> — ${cs(c.id).completed.length}/${SS_CONTENT[c.id].modules.length} stages, ${Object.keys(cs(c.id).reflections).length} written evidence item(s)</p>`).join('');$('portalPanel').innerHTML=out}
function openTutor(id){renderPortal();go('portal');let c=C.find(x=>x.id===id);$('portalPanel').innerHTML=`<h2>Tutor support</h2><p>Ask for human support with <b>${c.title}</b>. AI support will later handle routine learning help; tutors remain available for escalation and professional review.</p><button class="soft" id="backToCourse">← Back to course</button><textarea id="tutorMsg" placeholder="What do you need help with?"></textarea><button class="cta" id="sendTutor">Save support request</button><p id="tutorStatus"></p>`;$('backToCourse').onclick=()=>openCourse(id,currentModule);$('sendTutor').onclick=()=>{let t=$('tutorMsg').value.trim();if(!t)return;state.support=state.support||[];state.support.push({course:id,message:t,date:new Date().toISOString(),status:'Open'});save();$('tutorStatus').textContent='Support request saved ✓'}}
$('learner').onclick=()=>{if(!Object.values(state.entitlements||{}).some(x=>x?.status==='paid'))return alert('No active paid course is assigned to this learner yet.');renderPortal();go('portal')};$('admin').onclick=()=>go('adminpage');
function send(t){if(!t.trim())return;msgs.innerHTML+=`<p class="me">${t}</p><p>The secure AI connection point is reserved. The production AI must run server-side so no provider key is exposed in GitHub.</p>`;msg.value=''}$('send').onclick=()=>send(msg.value);document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>send(b.textContent));msg.onkeydown=e=>{if(e.key==='Enter')send(msg.value)};


// BUILD 7 — interim admin operations, manual enrolment and certificate workflow.
state.admin=state.admin||{learners:[],tutors:['Alex','Jamie'],certificates:[]};
function learnerName(){return state.profile?.name||'SS Training Learner'}
function adminPanel(title,html){let host=document.getElementById('adminWorkspace');if(!host)return;host.innerHTML=`<div class="admin-workspace"><div class="workspace-head"><h2>${title}</h2><button class="soft" id="closeWorkspace">Close</button></div>${html}</div>`;document.getElementById('closeWorkspace').onclick=()=>host.innerHTML='';host.scrollIntoView({behavior:'smooth'})}
function refreshAdmin(){let rows=state.admin.learners.map((l,i)=>`<tr><td>${l.name}</td><td>${l.email}</td><td>${(l.courses||[]).map(id=>C.find(c=>c.id==id)?.title||id).join(', ')||'—'}</td><td>${l.tutor||'—'}</td><td>${l.status||'Active'}</td></tr>`).join('')||'<tr><td colspan="5">No registered learners yet.</td></tr>';let tbody=document.getElementById('adminLearnerRows');if(tbody)tbody.innerHTML=rows}
function registerLearner(){adminPanel('Register learner',`<div class="formgrid"><label>Full name<input id="alName"></label><label>Email<input id="alEmail" type="email"></label><label>Status<select id="alStatus"><option>Active</option><option>Pending payment</option><option>Review</option></select></label></div><button class="cta" id="saveLearner">Register learner</button><p class="muted">Interim manual administration. Production accounts will be created and authenticated through Appwrite.</p>`);document.getElementById('saveLearner').onclick=()=>{let name=alName.value.trim(),email=alEmail.value.trim().toLowerCase();if(!name||!email)return alert('Enter the learner name and email.');if(state.admin.learners.some(x=>x.email===email))return alert('That learner is already registered.');state.admin.learners.push({name,email,status:alStatus.value,courses:[],tutor:'',created:new Date().toISOString()});save();refreshAdmin();adminPanel('Learner registered',`<p><b>${name}</b> has been added. You can now assign their paid course.</p>`)}}
function assignCourse(){let opts=state.admin.learners.map((l,i)=>`<option value="${i}">${l.name} — ${l.email}</option>`).join(''),courses=C.map(c=>`<option value="${c.id}">${c.title}</option>`).join('');adminPanel('Assign paid course',`<div class="formgrid"><label>Learner<select id="acLearner">${opts}</select></label><label>Course<select id="acCourse">${courses}</select></label></div><button class="cta" id="saveCourseAssign">Activate course</button><p class="muted">Use this after you have independently confirmed payment. This records a manual entitlement for the interim build.</p>`);saveCourseAssign.onclick=()=>{let l=state.admin.learners[+acLearner.value],id=+acCourse.value;if(!l)return alert('Register a learner first.');l.courses=l.courses||[];if(!l.courses.includes(id))l.courses.push(id);l.status='Active';state.entitlements[id]={status:'paid',source:'admin-manual',learnerEmail:l.email,at:new Date().toISOString()};state.profile={...state.profile,name:l.name,email:l.email};save();refreshAdmin();adminPanel('Course activated',`<p><b>${l.name}</b> is now assigned to <b>${C.find(c=>c.id===id).title}</b>.</p>`)}}
function assignTutor(){let opts=state.admin.learners.map((l,i)=>`<option value="${i}">${l.name}</option>`).join('');adminPanel('Assign tutor',`<div class="formgrid"><label>Learner<select id="atLearner">${opts}</select></label><label>Tutor<input id="atTutor" placeholder="Tutor name"></label></div><button class="cta" id="saveTutorAssign">Assign tutor</button>`);saveTutorAssign.onclick=()=>{let l=state.admin.learners[+atLearner.value];if(!l)return alert('Register a learner first.');let t=atTutor.value.trim();if(!t)return alert('Enter a tutor name.');l.tutor=t;save();refreshAdmin();adminPanel('Tutor assigned',`<p><b>${t}</b> has been assigned to <b>${l.name}</b>.</p>`)}}
function reviewWork(){let learners=state.admin.learners;adminPanel('Review learner work',learners.length?learners.map(l=>`<article class="review-card"><h3>${l.name}</h3><p>${l.email} • Tutor: ${l.tutor||'Not assigned'}</p><p>Assigned courses: ${(l.courses||[]).map(id=>C.find(c=>c.id==id)?.title).join(', ')||'None'}</p><p>Support requests: ${(state.support||[]).filter(x=>!x.learnerEmail||x.learnerEmail===l.email).length}</p></article>`).join(''):'<p>No learners registered yet.</p>')}
function certificatesAdmin(){let passed=C.filter(c=>owned(c.id)&&cs(c.id).finalScore>=80);adminPanel('Certificates',passed.length?passed.map(c=>`<article class="review-card"><h3>${learnerName()}</h3><p>${c.title} • ${c.hours} CPD hours • Score ${cs(c.id).finalScore}%</p><button class="cta certGenerate" data-course="${c.id}">Preview / print certificate</button></article>`).join(''):'<p>No certificates are ready yet. A learner must complete the course and achieve at least 80%.</p>');document.querySelectorAll('.certGenerate').forEach(b=>b.onclick=()=>showCertificate(+b.dataset.course))}
function showCertificate(id){let c=C.find(x=>x.id===id),s=cs(id),date=new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'}),ref=`SS-${new Date().getFullYear()}-${String(id).padStart(2,'0')}-${Math.abs((state.profile?.email||learnerName()).split('').reduce((a,x)=>((a<<5)-a)+x.charCodeAt(0),0)).toString().slice(0,6)}`;let html=`<div class="certificate" id="certificate"><div class="cert-logo">SS</div><div class="cert-brand">SS TRAINING<small>BARBERING • CPD • DEVELOPMENT</small></div><p class="cert-kicker">CERTIFICATE OF CONTINUING PROFESSIONAL DEVELOPMENT</p><h1>Certificate of Completion</h1><p>This certifies that</p><h2>${learnerName()}</h2><p>has successfully completed</p><h3>${c.title}</h3><div class="cert-meta"><span><b>${c.hours}</b> CPD hours</span><span><b>${s.finalScore}%</b> final assessment</span><span><b>${date}</b> completion date</span></div><p class="cert-ref">Certificate reference: ${ref}</p><div class="cert-sign"><span>SS Training<br><small>Professional Development</small></span><span>Verified completion<br><small>Digital training record</small></span></div></div><button class="cta" id="printCertificate">Print / Save as PDF</button>`;adminPanel('Certificate preview',html);printCertificate.onclick=()=>window.print()}
function wireAdminActions(){let map={registerLearner:registerLearner,assignCourse:assignCourse,assignTutor:assignTutor,reviewWork:reviewWork,adminCertificates:certificatesAdmin};Object.entries(map).forEach(([id,fn])=>{let el=document.getElementById(id);if(el)el.onclick=fn});refreshAdmin()}
setTimeout(wireAdminActions,500);
