let C=[]; let currentCourse=1; let currentModule=0;
const pages=[...document.querySelectorAll('.page')];
const $=id=>document.getElementById(id);
const storeKey='ssTrainingV2';
const state=JSON.parse(localStorage.getItem(storeKey)||'{"courses":{},"profile":{"name":"SS Learner"}}');
function save(){localStorage.setItem(storeKey,JSON.stringify(state))}
function go(id){pages.forEach(p=>p.classList.remove('active'));$(id)?.classList.add('active');scrollTo(0,0)}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
function cs(id){return state.courses[id]||(state.courses[id]={completed:[],answers:{},reflections:{},minutes:0,started:Date.now(),finalScore:null,feedback:null})}
fetch('courses.json').then(r=>r.json()).then(d=>{C=d;draw();renderPortal()});
function card(c){let s=cs(c.id), pct=Math.round((s.completed.length/(window.SS_CONTENT[c.id].modules.length))*100);return `<article class="card" data-id="${c.id}"><small>${c.tag.toUpperCase()} • ${c.hours} CPD HOURS</small><h3>${c.title}</h3><p>${c.desc}</p><div class="mini-progress"><b style="width:${pct}%"></b></div><footer><b>£${c.price}</b><button aria-label="Open course">→</button></footer></article>`}
function draw(){featured.innerHTML=C.slice(0,3).map(card).join('');grid.innerHTML=C.map(card).join('');document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>detail(+x.dataset.id))}
function detail(id){let c=C.find(x=>x.id===id), d=SS_CONTENT[id];detailbox.innerHTML=`<div class="detail"><div class="detailtop"><div><i>${c.tag.toUpperCase()} • SS TRAINING CPD</i><h1>${c.title}</h1><p>${c.desc}</p></div><aside class="buy"><b>£${c.price}</b><span>${c.hours} CPD hours</span><span>Online • self-paced</span><span>${d.modules.length} structured learning stages</span><span>Knowledge checks + final assessment</span><span>Reflection + learner feedback</span><span>SS Training certificate</span><button class="cta" id="startCourse">Open course →</button></aside></div><div class="twocol"><section><h2>What you'll develop</h2><ul>${d.outcomes.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><h2>Course pathway</h2><ol>${d.modules.map((x,i)=>`<li>${String(i+1).padStart(2,'0')} ${x.title}</li>`).join('')}</ol></section></div></div>`;go('detail');$('startCourse').onclick=()=>openCourse(id)}
function openCourse(id,idx){currentCourse=id;let s=cs(id), d=SS_CONTENT[id];currentModule=idx??Math.min(s.completed.length,d.modules.length-1);renderLesson();go('lesson')}
function renderLesson(){let d=SS_CONTENT[currentCourse], m=d.modules[currentModule], s=cs(currentCourse), last=d.modules.length-1;let done=s.completed.includes(currentModule);lesson.innerHTML=`<button class="back" id="dashBack">← Dashboard</button><div class="pagehero"><i>${d.short.toUpperCase()} • STAGE ${String(currentModule+1).padStart(2,'0')}</i><h1>${m.title}<br><em>${m.subtitle}</em></h1><p>${m.intro}</p></div><div class="learning"><div>${videoBlock(m)}<article><i>LEARNING</i><h2>${m.heading}</h2>${m.body.map(p=>`<p>${p}</p>`).join('')}${m.points?`<ul class="learn-list">${m.points.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}<blockquote>${m.takeaway}</blockquote></article>${m.quiz?quizBlock(m):''}${m.task?taskBlock(m,s):''}${currentModule===last?finalBlock(d,s):''}<div class="lesson-actions"><button class="soft" id="prevMod" ${currentModule===0?'disabled':''}>← Previous</button><button class="cta" id="completeMod">${done?'Completed ✓':'Complete stage'}</button><button class="soft" id="nextMod" ${currentModule===last?'disabled':''}>Next →</button></div></div><aside><i>COURSE PATHWAY</i>${d.modules.map((x,i)=>`<button class="path ${i===currentModule?'current':''} ${s.completed.includes(i)?'done':''}" data-mod="${i}">${s.completed.includes(i)?'✓':'○'} ${String(i+1).padStart(2,'0')} ${x.title}</button>`).join('')}<div class="help"><b>Need support?</b><small>Use tutor support when you need a person to review a learning or assessment question.</small><button id="askTutor">Ask tutor →</button></div></aside></div>`;
$('dashBack').onclick=()=>{renderPortal();go('portal')}; document.querySelectorAll('[data-mod]').forEach(b=>b.onclick=()=>openCourse(currentCourse,+b.dataset.mod));
$('prevMod').onclick=()=>openCourse(currentCourse,currentModule-1); $('nextMod').onclick=()=>openCourse(currentCourse,currentModule+1);
$('completeMod').onclick=()=>completeStage(m); $('askTutor').onclick=()=>openTutor(currentCourse);
wireQuiz(m); wireTask(m,s); if(currentModule===last)wireFinal(d,s);
}
function videoBlock(m){return `<div class="video">${m.video?`<iframe src="${m.video}" title="SS Training course video" allowfullscreen></iframe>`:`<b>▶</b><span>SS TRAINING VIDEO</span><small>Video slot ready — add the final SS Training demonstration URL in learning-data.js</small>`}</div>`}
function quizBlock(m){return `<article><i>KNOWLEDGE CHECK</i><h2>${m.quiz.q}</h2>${m.quiz.a.map((a,i)=>`<label><input type="radio" name="stageq" value="${i}"> ${a}</label>`).join('')}<button class="cta" id="checkStage">Check answer</button><p id="stageResult"></p></article>`}
function wireQuiz(m){if(!m.quiz)return;$('checkStage').onclick=()=>{let q=document.querySelector('input[name=stageq]:checked');if(!q)return $('stageResult').textContent='Choose an answer first.';let ok=+q.value===m.quiz.correct;$('stageResult').textContent=ok?'Correct — '+m.quiz.explain:'Not quite. '+m.quiz.explain;cs(currentCourse).answers[currentModule]=ok;save()}}
function taskBlock(m,s){return `<article><i>APPLY & REFLECT</i><h2>${m.task}</h2><textarea id="reflection" placeholder="Write your answer here...">${s.reflections[currentModule]||''}</textarea><button class="soft" id="saveReflection">Save progress</button><small class="save-note" id="saveNote"></small></article>`}
function wireTask(m,s){if(!m.task)return;$('saveReflection').onclick=()=>{s.reflections[currentModule]=$('reflection').value.trim();save();$('saveNote').textContent='Saved on this device ✓'}}
function completeStage(m){let s=cs(currentCourse);if(m.quiz&&!s.answers[currentModule])return alert('Please pass the knowledge check before completing this stage.');if(m.task){let v=$('reflection')?.value.trim()||s.reflections[currentModule];if(v.length<40)return alert('Please complete the reflection/activity with a little more detail first.');s.reflections[currentModule]=v}if(!s.completed.includes(currentModule))s.completed.push(currentModule);s.completed.sort((a,b)=>a-b);save();draw();if(currentModule<SS_CONTENT[currentCourse].modules.length-1)openCourse(currentCourse,currentModule+1);else renderLesson()}
function finalBlock(d,s){return `<article class="finalbox"><i>FINAL ASSESSMENT</i><h2>Final knowledge assessment</h2><p>Answer all questions. A score of 80% or above is required. You can retry.</p>${d.final.map((q,n)=>`<div class="finalq"><b>${n+1}. ${q.q}</b>${q.a.map((a,i)=>`<label><input type="radio" name="fq${n}" value="${i}"> ${a}</label>`).join('')}</div>`).join('')}<button class="cta" id="markFinal">Mark assessment</button><p id="finalResult">${s.finalScore===null?'':`Latest score: ${s.finalScore}%`}</p></article><article><i>COURSE FEEDBACK</i><h2>Help us improve SS Training</h2><label>How useful was this course?<select id="rating"><option value="">Choose</option><option>5 - Excellent</option><option>4 - Very good</option><option>3 - Good</option><option>2 - Fair</option><option>1 - Poor</option></select></label><textarea id="feedbackText" placeholder="What was most useful, and what could we improve?">${s.feedback?.text||''}</textarea><button class="soft" id="saveFeedback">Save feedback</button><p id="completionMessage"></p></article>`}
function wireFinal(d,s){$('markFinal').onclick=()=>{let score=0,answered=0;d.final.forEach((q,n)=>{let x=document.querySelector(`input[name=fq${n}]:checked`);if(x){answered++;if(+x.value===q.correct)score++}});if(answered<d.final.length)return alert('Please answer every final assessment question.');s.finalScore=Math.round(score/d.final.length*100);save();$('finalResult').textContent=`Score: ${s.finalScore}% — ${s.finalScore>=80?'Pass ✓':'Please review the course and try again.'}`;checkAward(d,s)};$('saveFeedback').onclick=()=>{s.feedback={rating:$('rating').value,text:$('feedbackText').value.trim(),date:new Date().toISOString()};save();checkAward(d,s)};checkAward(d,s)}
function checkAward(d,s){let ready=s.completed.length===d.modules.length&&s.finalScore>=80&&s.feedback?.rating;if($('completionMessage'))$('completionMessage').innerHTML=ready?`Course requirements complete. <button class="cta" id="certNow">View certificate →</button>`:'Complete every stage, pass the final assessment and submit feedback to unlock your certificate.';if(ready&&$('certNow'))$('certNow').onclick=()=>certificate(currentCourse)}
function renderPortal(){if(!C.length)return;let active=C.find(c=>cs(c.id).completed.length)||C[0],s=cs(active.id),d=SS_CONTENT[active.id],pct=Math.round(s.completed.length/d.modules.length*100);$('portal').innerHTML=`<div class="top"><div><i>LEARNER PORTAL</i><h1>Welcome back.</h1></div><button class="soft" data-page="home" id="signout">Sign out</button></div><div class="portal"><aside><button class="side active">◉ My Learning</button><button class="side" id="assessmentsBtn">○ Assessments</button><button class="side" id="tutorBtn">○ Tutor Support</button><button class="side" id="certBtn">○ Certificates</button><button class="side" id="portfolioBtn">○ Portfolio</button></aside><div><div class="continue"><i>CONTINUE LEARNING</i><h2>${active.title}</h2><p>Stage ${Math.min(s.completed.length+1,d.modules.length)} — ${d.modules[Math.min(s.completed.length,d.modules.length-1)].title}</p><div class="progress"><b style="width:${pct}%"></b></div><small>${pct}% complete • ${s.completed.length}/${d.modules.length} stages complete</small><button class="cta" id="continueCourse">Continue →</button></div><div class="stats"><span><b>${Object.values(state.courses).reduce((n,x)=>n+(x.completed?.length||0),0)}</b>Stages completed</span><span><b>${s.finalScore??'—'}${s.finalScore!==null?'%':''}</b>Final score</span><span><b>${C.filter(c=>cs(c.id).completed.length).length}</b>Active courses</span><span><b>Available</b>Tutor support</span></div><div id="portalPanel" class="portal-panel"></div></div></div>`;$('continueCourse').onclick=()=>openCourse(active.id);$('signout').onclick=()=>go('home');$('assessmentsBtn').onclick=()=>portalPanel('assess');$('tutorBtn').onclick=()=>openTutor(active.id);$('certBtn').onclick=()=>portalPanel('cert');$('portfolioBtn').onclick=()=>portalPanel('portfolio')}
function portalPanel(type){let out='';if(type==='assess')out='<h2>Assessments</h2>'+C.map(c=>`<p><b>${c.title}</b> — ${cs(c.id).finalScore===null?'Not attempted':cs(c.id).finalScore+'%'}</p>`).join('');if(type==='cert')out='<h2>Certificates</h2>'+C.map(c=>{let s=cs(c.id),d=SS_CONTENT[c.id],ok=s.completed.length===d.modules.length&&s.finalScore>=80&&s.feedback?.rating;return `<p><b>${c.title}</b> — ${ok?`<button onclick="certificate(${c.id})">View certificate</button>`:'Not yet unlocked'}</p>`}).join('');if(type==='portfolio')out='<h2>Learning portfolio</h2>'+C.map(c=>`<p><b>${c.title}</b> — ${cs(c.id).completed.length}/${SS_CONTENT[c.id].modules.length} stages, ${Object.keys(cs(c.id).reflections).length} saved reflections</p>`).join('');$('portalPanel').innerHTML=out}
function openTutor(id){let c=C.find(x=>x.id===id);$('portalPanel')?($('portalPanel').innerHTML=`<h2>Tutor support</h2><p>Ask for help with <b>${c.title}</b>. This form saves the request ready for your live email/Appwrite connection.</p><textarea id="tutorMsg" placeholder="What do you need help with?"></textarea><button class="cta" id="sendTutor">Save support request</button><p id="tutorStatus"></p>`):null;if($('portalPanel')){go('portal');$('sendTutor').onclick=()=>{let t=$('tutorMsg').value.trim();if(!t)return;state.support=state.support||[];state.support.push({course:id,message:t,date:new Date().toISOString(),status:'Open'});save();$('tutorStatus').textContent='Support request saved ✓'}}}
window.certificate=function(id){let c=C.find(x=>x.id===id),s=cs(id);let w=window.open('','_blank');w.document.write(`<html><head><title>SS Training Certificate</title><style>body{font-family:Arial;background:#0a0d12;color:white;display:grid;place-items:center;height:100vh;margin:0}.cert{width:900px;max-width:90%;padding:70px;border:2px solid #7895b5;text-align:center;background:linear-gradient(135deg,#101824,#241217)}h1{font-size:58px;margin:20px}h2{font-size:30px}p{color:#bbc3cc;font-size:18px}.hours{font-size:28px;color:white}.line{border-top:1px solid #777;margin:50px auto 10px;width:300px}@media print{button{display:none}}</style></head><body><div class="cert"><small>SS TRAINING • BARBERING • CPD • DEVELOPMENT</small><h1>Certificate of Completion</h1><p>This certifies that</p><h2>${state.profile.name||'SS Training Learner'}</h2><p>has successfully completed</p><h2>${c.title}</h2><p class="hours">10 CPD HOURS</p><p>Knowledge assessment: ${s.finalScore}% • Completed ${new Date().toLocaleDateString('en-GB')}</p><div class="line"></div><p>SS Training</p><button onclick="print()">Print / Save PDF</button></div></body></html>`);w.document.close()}
// Login remains development-mode until Appwrite credentials are added.
$('learner').onclick=()=>{renderPortal();go('portal')};$('admin').onclick=()=>go('adminpage');
function send(t){if(!t.trim())return;msgs.innerHTML+=`<p class="me">${t}</p><p>Thanks. The course assistant connection point is ready, but a secure server-side AI key is still required before this can answer live without exposing credentials.</p>`;msg.value=''}$('send').onclick=()=>send(msg.value);document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>send(b.textContent));msg.onkeydown=e=>{if(e.key==='Enter')send(msg.value)};
